language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
install:
    - pip install zc.buildout
    - buildlout
script:
    - bin/test
    - cd doc; make SPHINXBUILD=../bin/sphinx-build doctest
notifications:
    email: false
